from components.debug import Debug

from components.position import Position
from components.renderable import Renderable
from components.input import Input
from components.player import Player
from components.level import Level
from components.fov import FOV
from components.light import Light
from components.damageable import Damageable
from components.info import Info
from components.melee import Melee
from components.blocking import Blocking
from components.ai import AI
from components.inventory import Inventory 
from components.item import Item
from components.trigger import Trigger
from components.equipment import Equipment
from components.actor import Actor